SELECT
    TO_NUMBER(TO_CHAR(DATETIME, 'hh24')) HOUR,
    COUNT(*) COUNT
FROM
    ANIMAL_OUTS
WHERE
    TO_NUMBER(TO_CHAR(DATETIME, 'hh24')) BETWEEN 9 AND 20
GROUP BY
    TO_NUMBER(TO_CHAR(DATETIME, 'hh24'))
ORDER BY
    HOUR